### ISSUE TITLE
Fatal error: unable to find bundle named Bugle_Bugle

### ISSUE THREAD

**Issue by yenamax** [ABridoux/bugle#13]
Hi,

I'm running macOS Big Sur 11.5.1 (20G80).
I tried to run bugle manually and from the package you provided, but every time I try to run the commands in the example I'm getting the following error :

> bugle domains kerberos
Bugle/resource_bundle_accessor.swift:27: Fatal error: unable to find bundle named Bugle_Bugle
[1]    4732 illegal hardware instruction  bugle domains kerberos

Am I doing something wrong ? 

Thank you for your feedback.

**Comment by ABridoux** [comment]
Hi ! Sorry for the late answer, I did not get any notification for that.
You say you try to run it manually. You mean you build it with the `swift` command ?

**Comment by ABridoux** [comment]
This seems to be an error related to Swift 5.3. I'll release a new version of Bugle to fix that.

**Comment by ABridoux** [comment]
Closing issue after resolution (release 0.2.1)
